In [1]:
import lsdb

In [2]:
cat = lsdb.open_catalog("../tests/data/small_sky_order1_collection")
cat

lsdb Catalog small_sky_order1:
                                 id               ra              dec        ra_error       dec_error
npartitions=4
Order: 1, Pixel: 44  int64[pyarrow]  double[pyarrow]  double[pyarrow]  int64[pyarrow]  int64[pyarrow]
Order: 1, Pixel: 45             ...              ...              ...             ...             ...
Order: 1, Pixel: 46             ...              ...              ...             ...             ...
Order: 1, Pixel: 47             ...              ...              ...             ...             ...
5 out of 5 available columns in the catalog have been loaded lazily, meaning no data has been read, only the catalog schema
This catalog has an estimated size of 31.7 KB

In [3]:
cat.compute()

Computing Catalog:   0%|          | 0/4 [00:00<?, ?it/s]

                      id     ra   dec  ra_error  dec_error
_healpix_29
3187422220182231470  707  308.5 -69.5         0          0
3187796123455121090  792  320.5 -69.5         0          0
...                  ...    ...   ...       ...        ...
3400255793565258227  767  314.5 -29.5         0          0
3424180623569024089  743  307.5 -25.5         0          0

[131 rows x 5 columns]

In [4]:
from distributed import Client

In [5]:
with Client() as client:
    cat.compute()

Computing Catalog:   0%|          | 0/4 [00:00<?, ?it/s]

In [6]:
cat.write_catalog("/tmp/small_sky_order1_collection_copy", overwrite=True)

Writing Catalog:   0%|          | 0/8 [00:00<?, ?it/s]

Writing Margin Cache:   0%|          | 0/10 [00:00<?, ?it/s]

In [7]:
with Client() as client:
    cat.write_catalog("/tmp/small_sky_order1_collection_copy", overwrite=True)

Writing Catalog:   0%|          | 0/4 [00:00<?, ?it/s]

Writing Margin Cache:   0%|          | 0/5 [00:00<?, ?it/s]