## Aggregate column statistics - before

Simply uses the version of `hats` before any of this `per_partition_statistics` nonsense even started.

In [1]:
import hats

In [2]:
hats.__version__

'0.9.1.dev1+g13819050a.d20260326'

In [3]:
%%time
gaia_http = hats.read_hats("https://data.lsdb.io/hats/gaia_dr3/gaia/")

CPU times: user 101 ms, sys: 70.6 ms, total: 172 ms
Wall time: 2.88 s

In [4]:
%%time
gaia_http.aggregate_column_statistics()

CPU times: user 10.5 s, sys: 1.08 s, total: 11.6 s
Wall time: 22.4 s

,min_value,max_value,null_count,row_count
column_names,,,,
solution_id,1636148068921376768,1636148068921376768,0,1812731847
designation,Gaia DR3 1000000057322000000,Gaia DR3 999999988604363776,0,1812731847
...,...,...,...,...
ebpminrp_gspphot_upper,9.999999747378752e-05,4.226200103759766,1341620712,1812731847
libname_gspphot,A,PHOENIX,1341620712,1812731847

In [5]:
%%time
gaia_http.per_pixel_statistics()

CPU times: user 12.1 s, sys: 686 ms, total: 12.8 s
Wall time: 22.1 s

,solution_id: min_value,solution_id: max_value,solution_id: null_count,solution_id: row_count,solution_id: disk_bytes,solution_id: memory_bytes,designation: min_value,designation: max_value,designation: null_count,designation: row_count,...,ebpminrp_gspphot_upper: null_count,ebpminrp_gspphot_upper: row_count,ebpminrp_gspphot_upper: disk_bytes,ebpminrp_gspphot_upper: memory_bytes,libname_gspphot: min_value,libname_gspphot: max_value,libname_gspphot: null_count,libname_gspphot: row_count,libname_gspphot: disk_bytes,libname_gspphot: memory_bytes
"Order: 2, Pixel: 0",1636148068921376768,1636148068921376768,0,726621,464,392,Gaia DR3 10000023895138176,Gaia DR3 9999920815921280,0,726621,...,427414,726621,671659,699976,A,PHOENIX,427414,726621,142318,170015
"Order: 2, Pixel: 1",1636148068921376768,1636148068921376768,0,1485249,928,784,Gaia DR3 110382721092038400,Gaia DR3 72057563974342016,0,1485249,...,886858,1485249,1364617,1423445,A,PHOENIX,886858,1485249,292048,344618
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"Order: 3, Pixel: 766",1636148068921376768,1636148068921376768,0,1110599,696,588,Gaia DR3 4215380800385843200,Gaia DR3 6914504271159215360,0,1110599,...,702590,1110599,842993,908891,A,PHOENIX,702590,1110599,205353,249362
"Order: 3, Pixel: 767",1636148068921376768,1636148068921376768,0,820930,580,490,Gaia DR3 2688741680114353664,Gaia DR3 6917528997577384320,0,820930,...,517771,820930,640619,682846,A,PHOENIX,517771,820930,152771,184938