## Aggregate column statistics - after

`issue/607/row-group` branch, which prefers to use the `per_partition_statistics.parquet` file when available, both for `aggregate_column_statistics` and `per_pixel_statistics` methods.

In [1]:
import hats

In [2]:
hats.__version__

'0.9.1.dev11+g94071f98f'

In [3]:
%%time
gaia_http = hats.read_hats("https://data.lsdb.io/hats/gaia_dr3/gaia/")

CPU times: user 98.1 ms, sys: 67.5 ms, total: 166 ms
Wall time: 3.04 s

In [4]:
%%time
gaia_http.aggregate_column_statistics()

CPU times: user 1.11 s, sys: 250 ms, total: 1.36 s
Wall time: 3.7 s

,min_value,max_value,null_count,row_count
column_names,,,,
solution_id,1636148068921376768,1636148068921376768,0,1812731847
designation,Gaia DR3 1000000057322000000,Gaia DR3 999999988604363776,0,1812731847
...,...,...,...,...
ebpminrp_gspphot_upper,0.0001,4.2262,1341620712,1812731847
libname_gspphot,A,PHOENIX,1341620712,1812731847

In [5]:
%%time
gaia_http.per_pixel_statistics()

<timed eval>:1: DeprecationWarning: Call to deprecated method per_pixel_statistics. (`per_pixel_statistics` will be removed in the future, use `per_partition_statistics` instead.) -- Deprecated since version 0.9.1.

CPU times: user 13.6 s, sys: 393 ms, total: 14 s
Wall time: 16.8 s

,solution_id: min_value,solution_id: max_value,solution_id: null_count,solution_id: row_count,solution_id: disk_bytes,solution_id: memory_bytes,designation: min_value,designation: max_value,designation: null_count,designation: row_count,designation: disk_bytes,designation: memory_bytes,source_id: min_value,source_id: max_value,source_id: null_count,source_id: row_count,source_id: disk_bytes,source_id: memory_bytes,random_index: min_value,random_index: max_value,random_index: null_count,random_index: row_count,random_index: disk_bytes,random_index: memory_bytes,ref_epoch: min_value,ref_epoch: max_value,ref_epoch: null_count,ref_epoch: row_count,ref_epoch: disk_bytes,ref_epoch: memory_bytes,ra: min_value,ra: max_value,ra: null_count,ra: row_count,ra: disk_bytes,ra: memory_bytes,ra_error: min_value,ra_error: max_value,ra_error: null_count,ra_error: row_count,ra_error: disk_bytes,ra_error: memory_bytes,dec: min_value,dec: max_value,dec: null_count,dec: row_count,dec: disk_bytes,dec: memory_bytes,dec_error: min_value,dec_error: max_value,dec_error: null_count,dec_error: row_count,dec_error: disk_bytes,dec_error: memory_bytes,parallax: min_value,parallax: max_value,parallax: null_count,parallax: row_count,parallax: disk_bytes,parallax: memory_bytes,parallax_error: min_value,parallax_error: max_value,parallax_error: null_count,parallax_error: row_count,parallax_error: disk_bytes,parallax_error: memory_bytes,parallax_over_error: min_value,parallax_over_error: max_value,parallax_over_error: null_count,parallax_over_error: row_count,parallax_over_error: disk_bytes,parallax_over_error: memory_bytes,pm: min_value,pm: max_value,pm: null_count,pm: row_count,pm: disk_bytes,pm: memory_bytes,pmra: min_value,pmra: max_value,pmra: null_count,pmra: row_count,pmra: disk_bytes,pmra: memory_bytes,pmra_error: min_value,pmra_error: max_value,pmra_error: null_count,pmra_error: row_count,pmra_error: disk_bytes,pmra_error: memory_bytes,pmdec: min_value,pmdec: max_value,pmdec: null_count,pmdec: row_count,pmdec: disk_bytes,pmdec: memory_bytes,pmdec_error: min_value,pmdec_error: max_value,pmdec_error: null_count,pmdec_error: row_count,pmdec_error: disk_bytes,pmdec_error: memory_bytes,ra_dec_corr: min_value,ra_dec_corr: max_value,ra_dec_corr: null_count,ra_dec_corr: row_count,ra_dec_corr: disk_bytes,ra_dec_corr: memory_bytes,ra_parallax_corr: min_value,ra_parallax_corr: max_value,ra_parallax_corr: null_count,ra_parallax_corr: row_count,ra_parallax_corr: disk_bytes,ra_parallax_corr: memory_bytes,ra_pmra_corr: min_value,ra_pmra_corr: max_value,ra_pmra_corr: null_count,ra_pmra_corr: row_count,ra_pmra_corr: disk_bytes,ra_pmra_corr: memory_bytes,ra_pmdec_corr: min_value,ra_pmdec_corr: max_value,ra_pmdec_corr: null_count,ra_pmdec_corr: row_count,ra_pmdec_corr: disk_bytes,ra_pmdec_corr: memory_bytes,dec_parallax_corr: min_value,dec_parallax_corr: max_value,dec_parallax_corr: null_count,dec_parallax_corr: row_count,dec_parallax_corr: disk_bytes,dec_parallax_corr: memory_bytes,dec_pmra_corr: min_value,dec_pmra_corr: max_value,dec_pmra_corr: null_count,dec_pmra_corr: row_count,dec_pmra_corr: disk_bytes,dec_pmra_corr: memory_bytes,dec_pmdec_corr: min_value,dec_pmdec_corr: max_value,dec_pmdec_corr: null_count,dec_pmdec_corr: row_count,dec_pmdec_corr: disk_bytes,dec_pmdec_corr: memory_bytes,parallax_pmra_corr: min_value,parallax_pmra_corr: max_value,parallax_pmra_corr: null_count,parallax_pmra_corr: row_count,parallax_pmra_corr: disk_bytes,parallax_pmra_corr: memory_bytes,parallax_pmdec_corr: min_value,parallax_pmdec_corr: max_value,parallax_pmdec_corr: null_count,parallax_pmdec_corr: row_count,parallax_pmdec_corr: disk_bytes,parallax_pmdec_corr: memory_bytes,pmra_pmdec_corr: min_value,pmra_pmdec_corr: max_value,pmra_pmdec_corr: null_count,pmra_pmdec_corr: row_count,pmra_pmdec_corr: disk_bytes,pmra_pmdec_corr: memory_bytes,astrometric_n_obs_al: min_value,astrometric_n_obs_al: max_value,astrometric_n_obs_al: null_count,astrometric_n_obs_al: row_count,astrometric_n_obs_al: disk_bytes,astrometric_n_obs_al: memory_bytes,astrometric_n_obs_ac: min_value,astrometric_n_obs_ac: max_value,astrometric_n_obs_ac: null_count,astrometric_n_obs_ac: row_count,astrometric_n_obs_ac: disk_bytes,astrometric_n_obs_ac: memory_bytes,astrometric_n_good_obs_al: min_value,astrometric_n_good_obs_al: max_value,astrometric_n_good_obs_al: null_count,astrometric_n_good_obs_al: row_count,astrometric_n_good_obs_al: disk_bytes,astrometric_n_good_obs_al: memory_bytes,astrometric_n_bad_obs_al: min_value,astrometric_n_bad_obs_al: max_value,astrometric_n_bad_obs_al: null_count,astrometric_n_bad_obs_al: row_count,astrometric_n_bad_obs_al: disk_bytes,astrometric_n_bad_obs_al: memory_bytes,astrometric_gof_al: min_value,astrometric_gof_al: max_value,astrometric_gof_al: null_count,astrometric_gof_al: row_count,astrometric_gof_al: disk_bytes,astrometric_gof_al: memory_bytes,astrometric_chi2_al: min_value,astrometric_chi2_al: max_value,astrometric_chi2_al: null_count,astrometric_chi2_al: row_count,astrometric_chi2_al: disk_bytes,astrometric_chi2_al: memory_bytes,astrometric_excess_noise: min_value,astrometric_excess_noise: max_value,astrometric_excess_noise: null_count,astrometric_excess_noise: row_count,astrometric_excess_noise: disk_bytes,astrometric_excess_noise: memory_bytes,astrometric_excess_noise_sig: min_value,astrometric_excess_noise_sig: max_value,astrometric_excess_noise_sig: null_count,astrometric_excess_noise_sig: row_count,astrometric_excess_noise_sig: disk_bytes,astrometric_excess_noise_sig: memory_bytes,astrometric_params_solved: min_value,astrometric_params_solved: max_value,astrometric_params_solved: null_count,astrometric_params_solved: row_count,astrometric_params_solved: disk_bytes,astrometric_params_solved: memory_bytes,astrometric_primary_flag: min_value,astrometric_primary_flag: max_value,astrometric_primary_flag: null_count,astrometric_primary_flag: row_count,astrometric_primary_flag: disk_bytes,astrometric_primary_flag: memory_bytes,nu_eff_used_in_astrometry: min_value,nu_eff_used_in_astrometry: max_value,nu_eff_used_in_astrometry: null_count,nu_eff_used_in_astrometry: row_count,nu_eff_used_in_astrometry: disk_bytes,nu_eff_used_in_astrometry: memory_bytes,pseudocolour: min_value,pseudocolour: max_value,pseudocolour: null_count,pseudocolour: row_count,pseudocolour: disk_bytes,pseudocolour: memory_bytes,pseudocolour_error: min_value,pseudocolour_error: max_value,pseudocolour_error: null_count,pseudocolour_error: row_count,pseudocolour_error: disk_bytes,pseudocolour_error: memory_bytes,ra_pseudocolour_corr: min_value,ra_pseudocolour_corr: max_value,ra_pseudocolour_corr: null_count,ra_pseudocolour_corr: row_count,ra_pseudocolour_corr: disk_bytes,ra_pseudocolour_corr: memory_bytes,dec_pseudocolour_corr: min_value,dec_pseudocolour_corr: max_value,dec_pseudocolour_corr: null_count,dec_pseudocolour_corr: row_count,dec_pseudocolour_corr: disk_bytes,dec_pseudocolour_corr: memory_bytes,parallax_pseudocolour_corr: min_value,parallax_pseudocolour_corr: max_value,parallax_pseudocolour_corr: null_count,parallax_pseudocolour_corr: row_count,parallax_pseudocolour_corr: disk_bytes,parallax_pseudocolour_corr: memory_bytes,pmra_pseudocolour_corr: min_value,pmra_pseudocolour_corr: max_value,pmra_pseudocolour_corr: null_count,pmra_pseudocolour_corr: row_count,pmra_pseudocolour_corr: disk_bytes,pmra_pseudocolour_corr: memory_bytes,pmdec_pseudocolour_corr: min_value,pmdec_pseudocolour_corr: max_value,pmdec_pseudocolour_corr: null_count,pmdec_pseudocolour_corr: row_count,pmdec_pseudocolour_corr: disk_bytes,pmdec_pseudocolour_corr: memory_bytes,astrometric_matched_transits: min_value,astrometric_matched_transits: max_value,astrometric_matched_transits: null_count,astrometric_matched_transits: row_count,astrometric_matched_transits: disk_bytes,astrometric_matched_transits: memory_bytes,visibility_periods_used: min_value,visibility_periods_used: max_value,visibility_periods_used: null_count,visibility_periods_used: row_count,visibility_periods_used: disk_bytes,visibility_periods_used: memory_bytes,astrometric_sigma5d_max: min_value,astrometric_sigma5d_max: max_value,astrometric_sigma5d_max: null_count,astrometric_sigma5d_max: row_count,astrometric_sigma5d_max: disk_bytes,astrometric_sigma5d_max: memory_bytes,matched_transits: min_value,matched_transits: max_value,matched_transits: null_count,matched_transits: row_count,matched_transits: disk_bytes,matched_transits: memory_bytes,new_matched_transits: min_value,new_matched_transits: max_value,new_matched_transits: null_count,new_matched_transits: row_count,new_matched_transits: disk_bytes,new_matched_transits: memory_bytes,matched_transits_removed: min_value,matched_transits_removed: max_value,matched_transits_removed: null_count,matched_transits_removed: row_count,matched_transits_removed: disk_bytes,matched_transits_removed: memory_bytes,ipd_gof_harmonic_amplitude: min_value,ipd_gof_harmonic_amplitude: max_value,ipd_gof_harmonic_amplitude: null_count,ipd_gof_harmonic_amplitude: row_count,ipd_gof_harmonic_amplitude: disk_bytes,ipd_gof_harmonic_amplitude: memory_bytes,ipd_gof_harmonic_phase: min_value,ipd_gof_harmonic_phase: max_value,ipd_gof_harmonic_phase: null_count,ipd_gof_harmonic_phase: row_count,ipd_gof_harmonic_phase: disk_bytes,ipd_gof_harmonic_phase: memory_bytes,ipd_frac_multi_peak: min_value,ipd_frac_multi_peak: max_value,ipd_frac_multi_peak: null_count,ipd_frac_multi_peak: row_count,ipd_frac_multi_peak: disk_bytes,ipd_frac_multi_peak: memory_bytes,ipd_frac_odd_win: min_value,ipd_frac_odd_win: max_value,ipd_frac_odd_win: null_count,ipd_frac_odd_win: row_count,ipd_frac_odd_win: disk_bytes,ipd_frac_odd_win: memory_bytes,ruwe: min_value,ruwe: max_value,ruwe: null_count,ruwe: row_count,ruwe: disk_bytes,ruwe: memory_bytes,scan_direction_strength_k1: min_value,scan_direction_strength_k1: max_value,scan_direction_strength_k1: null_count,scan_direction_strength_k1: row_count,scan_direction_strength_k1: disk_bytes,scan_direction_strength_k1: memory_bytes,scan_direction_strength_k2: min_value,scan_direction_strength_k2: max_value,scan_direction_strength_k2: null_count,scan_direction_strength_k2: row_count,scan_direction_strength_k2: disk_bytes,scan_direction_strength_k2: memory_bytes,scan_direction_strength_k3: min_value,scan_direction_strength_k3: max_value,scan_direction_strength_k3: null_count,scan_direction_strength_k3: row_count,scan_direction_strength_k3: disk_bytes,scan_direction_strength_k3: memory_bytes,scan_direction_strength_k4: min_value,scan_direction_strength_k4: max_value,scan_direction_strength_k4: null_count,scan_direction_strength_k4: row_count,scan_direction_strength_k4: disk_bytes,scan_direction_strength_k4: memory_bytes,scan_direction_mean_k1: min_value,scan_direction_mean_k1: max_value,scan_direction_mean_k1: null_count,scan_direction_mean_k1: row_count,scan_direction_mean_k1: disk_bytes,scan_direction_mean_k1: memory_bytes,scan_direction_mean_k2: min_value,scan_direction_mean_k2: max_value,scan_direction_mean_k2: null_count,scan_direction_mean_k2: row_count,scan_direction_mean_k2: disk_bytes,scan_direction_mean_k2: memory_bytes,scan_direction_mean_k3: min_value,scan_direction_mean_k3: max_value,scan_direction_mean_k3: null_count,scan_direction_mean_k3: row_count,scan_direction_mean_k3: disk_bytes,scan_direction_mean_k3: memory_bytes,scan_direction_mean_k4: min_value,scan_direction_mean_k4: max_value,scan_direction_mean_k4: null_count,scan_direction_mean_k4: row_count,scan_direction_mean_k4: disk_bytes,scan_direction_mean_k4: memory_bytes,duplicated_source: min_value,duplicated_source: max_value,duplicated_source: null_count,duplicated_source: row_count,duplicated_source: disk_bytes,duplicated_source: memory_bytes,phot_g_n_obs: min_value,phot_g_n_obs: max_value,phot_g_n_obs: null_count,phot_g_n_obs: row_count,phot_g_n_obs: disk_bytes,phot_g_n_obs: memory_bytes,phot_g_mean_flux: min_value,phot_g_mean_flux: max_value,phot_g_mean_flux: null_count,phot_g_mean_flux: row_count,phot_g_mean_flux: disk_bytes,phot_g_mean_flux: memory_bytes,phot_g_mean_flux_error: min_value,phot_g_mean_flux_error: max_value,phot_g_mean_flux_error: null_count,phot_g_mean_flux_error: row_count,phot_g_mean_flux_error: disk_bytes,phot_g_mean_flux_error: memory_bytes,phot_g_mean_flux_over_error: min_value,phot_g_mean_flux_over_error: max_value,phot_g_mean_flux_over_error: null_count,phot_g_mean_flux_over_error: row_count,phot_g_mean_flux_over_error: disk_bytes,phot_g_mean_flux_over_error: memory_bytes,phot_g_mean_mag: min_value,phot_g_mean_mag: max_value,phot_g_mean_mag: null_count,phot_g_mean_mag: row_count,phot_g_mean_mag: disk_bytes,phot_g_mean_mag: memory_bytes,phot_bp_n_obs: min_value,phot_bp_n_obs: max_value,phot_bp_n_obs: null_count,phot_bp_n_obs: row_count,phot_bp_n_obs: disk_bytes,phot_bp_n_obs: memory_bytes,phot_bp_mean_flux: min_value,phot_bp_mean_flux: max_value,phot_bp_mean_flux: null_count,phot_bp_mean_flux: row_count,phot_bp_mean_flux: disk_bytes,phot_bp_mean_flux: memory_bytes,phot_bp_mean_flux_error: min_value,phot_bp_mean_flux_error: max_value,phot_bp_mean_flux_error: null_count,phot_bp_mean_flux_error: row_count,phot_bp_mean_flux_error: disk_bytes,phot_bp_mean_flux_error: memory_bytes,phot_bp_mean_flux_over_error: min_value,phot_bp_mean_flux_over_error: max_value,phot_bp_mean_flux_over_error: null_count,phot_bp_mean_flux_over_error: row_count,phot_bp_mean_flux_over_error: disk_bytes,phot_bp_mean_flux_over_error: memory_bytes,phot_bp_mean_mag: min_value,phot_bp_mean_mag: max_value,phot_bp_mean_mag: null_count,phot_bp_mean_mag: row_count,phot_bp_mean_mag: disk_bytes,phot_bp_mean_mag: memory_bytes,phot_rp_n_obs: min_value,phot_rp_n_obs: max_value,phot_rp_n_obs: null_count,phot_rp_n_obs: row_count,phot_rp_n_obs: disk_bytes,phot_rp_n_obs: memory_bytes,phot_rp_mean_flux: min_value,phot_rp_mean_flux: max_value,phot_rp_mean_flux: null_count,phot_rp_mean_flux: row_count,phot_rp_mean_flux: disk_bytes,phot_rp_mean_flux: memory_bytes,phot_rp_mean_flux_error: min_value,phot_rp_mean_flux_error: max_value,phot_rp_mean_flux_error: null_count,phot_rp_mean_flux_error: row_count,phot_rp_mean_flux_error: disk_bytes,phot_rp_mean_flux_error: memory_bytes,phot_rp_mean_flux_over_error: min_value,phot_rp_mean_flux_over_error: max_value,phot_rp_mean_flux_over_error: null_count,phot_rp_mean_flux_over_error: row_count,phot_rp_mean_flux_over_error: disk_bytes,phot_rp_mean_flux_over_error: memory_bytes,phot_rp_mean_mag: min_value,phot_rp_mean_mag: max_value,phot_rp_mean_mag: null_count,phot_rp_mean_mag: row_count,phot_rp_mean_mag: disk_bytes,phot_rp_mean_mag: memory_bytes,phot_bp_rp_excess_factor: min_value,phot_bp_rp_excess_factor: max_value,phot_bp_rp_excess_factor: null_count,phot_bp_rp_excess_factor: row_count,phot_bp_rp_excess_factor: disk_bytes,phot_bp_rp_excess_factor: memory_bytes,phot_bp_n_contaminated_transits: min_value,phot_bp_n_contaminated_transits: max_value,phot_bp_n_contaminated_transits: null_count,phot_bp_n_contaminated_transits: row_count,phot_bp_n_contaminated_transits: disk_bytes,phot_bp_n_contaminated_transits: memory_bytes,phot_bp_n_blended_transits: min_value,phot_bp_n_blended_transits: max_value,phot_bp_n_blended_transits: null_count,phot_bp_n_blended_transits: row_count,phot_bp_n_blended_transits: disk_bytes,phot_bp_n_blended_transits: memory_bytes,phot_rp_n_contaminated_transits: min_value,phot_rp_n_contaminated_transits: max_value,phot_rp_n_contaminated_transits: null_count,phot_rp_n_contaminated_transits: row_count,phot_rp_n_contaminated_transits: disk_bytes,phot_rp_n_contaminated_transits: memory_bytes,phot_rp_n_blended_transits: min_value,phot_rp_n_blended_transits: max_value,phot_rp_n_blended_transits: null_count,phot_rp_n_blended_transits: row_count,phot_rp_n_blended_transits: disk_bytes,phot_rp_n_blended_transits: memory_bytes,phot_proc_mode: min_value,phot_proc_mode: max_value,phot_proc_mode: null_count,phot_proc_mode: row_count,phot_proc_mode: disk_bytes,phot_proc_mode: memory_bytes,bp_rp: min_value,bp_rp: max_value,bp_rp: null_count,bp_rp: row_count,bp_rp: disk_bytes,bp_rp: memory_bytes,bp_g: min_value,bp_g: max_value,bp_g: null_count,bp_g: row_count,bp_g: disk_bytes,bp_g: memory_bytes,g_rp: min_value,g_rp: max_value,g_rp: null_count,g_rp: row_count,g_rp: disk_bytes,g_rp: memory_bytes,radial_velocity: min_value,radial_velocity: max_value,radial_velocity: null_count,radial_velocity: row_count,radial_velocity: disk_bytes,radial_velocity: memory_bytes,radial_velocity_error: min_value,radial_velocity_error: max_value,radial_velocity_error: null_count,radial_velocity_error: row_count,radial_velocity_error: disk_bytes,radial_velocity_error: memory_bytes,rv_method_used: min_value,rv_method_used: max_value,rv_method_used: null_count,rv_method_used: row_count,rv_method_used: disk_bytes,rv_method_used: memory_bytes,rv_nb_transits: min_value,rv_nb_transits: max_value,rv_nb_transits: null_count,rv_nb_transits: row_count,rv_nb_transits: disk_bytes,rv_nb_transits: memory_bytes,rv_nb_deblended_transits: min_value,rv_nb_deblended_transits: max_value,rv_nb_deblended_transits: null_count,rv_nb_deblended_transits: row_count,rv_nb_deblended_transits: disk_bytes,rv_nb_deblended_transits: memory_bytes,rv_visibility_periods_used: min_value,rv_visibility_periods_used: max_value,rv_visibility_periods_used: null_count,rv_visibility_periods_used: row_count,rv_visibility_periods_used: disk_bytes,rv_visibility_periods_used: memory_bytes,rv_expected_sig_to_noise: min_value,rv_expected_sig_to_noise: max_value,rv_expected_sig_to_noise: null_count,rv_expected_sig_to_noise: row_count,rv_expected_sig_to_noise: disk_bytes,rv_expected_sig_to_noise: memory_bytes,rv_renormalised_gof: min_value,rv_renormalised_gof: max_value,rv_renormalised_gof: null_count,rv_renormalised_gof: row_count,rv_renormalised_gof: disk_bytes,rv_renormalised_gof: memory_bytes,rv_chisq_pvalue: min_value,rv_chisq_pvalue: max_value,rv_chisq_pvalue: null_count,rv_chisq_pvalue: row_count,rv_chisq_pvalue: disk_bytes,rv_chisq_pvalue: memory_bytes,rv_time_duration: min_value,rv_time_duration: max_value,rv_time_duration: null_count,rv_time_duration: row_count,rv_time_duration: disk_bytes,rv_time_duration: memory_bytes,rv_amplitude_robust: min_value,rv_amplitude_robust: max_value,rv_amplitude_robust: null_count,rv_amplitude_robust: row_count,rv_amplitude_robust: disk_bytes,rv_amplitude_robust: memory_bytes,rv_template_teff: min_value,rv_template_teff: max_value,rv_template_teff: null_count,rv_template_teff: row_count,rv_template_teff: disk_bytes,rv_template_teff: memory_bytes,rv_template_logg: min_value,rv_template_logg: max_value,rv_template_logg: null_count,rv_template_logg: row_count,rv_template_logg: disk_bytes,rv_template_logg: memory_bytes,rv_template_fe_h: min_value,rv_template_fe_h: max_value,rv_template_fe_h: null_count,rv_template_fe_h: row_count,rv_template_fe_h: disk_bytes,rv_template_fe_h: memory_bytes,rv_atm_param_origin: min_value,rv_atm_param_origin: max_value,rv_atm_param_origin: null_count,rv_atm_param_origin: row_count,rv_atm_param_origin: disk_bytes,rv_atm_param_origin: memory_bytes,vbroad: min_value,vbroad: max_value,vbroad: null_count,vbroad: row_count,vbroad: disk_bytes,vbroad: memory_bytes,vbroad_error: min_value,vbroad_error: max_value,vbroad_error: null_count,vbroad_error: row_count,vbroad_error: disk_bytes,vbroad_error: memory_bytes,vbroad_nb_transits: min_value,vbroad_nb_transits: max_value,vbroad_nb_transits: null_count,vbroad_nb_transits: row_count,vbroad_nb_transits: disk_bytes,vbroad_nb_transits: memory_bytes,grvs_mag: min_value,grvs_mag: max_value,grvs_mag: null_count,grvs_mag: row_count,grvs_mag: disk_bytes,grvs_mag: memory_bytes,grvs_mag_error: min_value,grvs_mag_error: max_value,grvs_mag_error: null_count,grvs_mag_error: row_count,grvs_mag_error: disk_bytes,grvs_mag_error: memory_bytes,grvs_mag_nb_transits: min_value,grvs_mag_nb_transits: max_value,grvs_mag_nb_transits: null_count,grvs_mag_nb_transits: row_count,grvs_mag_nb_transits: disk_bytes,grvs_mag_nb_transits: memory_byt