In [1]:
import lsdb

In [2]:
cat = lsdb.open_catalog("../tests/data/small_sky_order1_collection")
cat

FromHealpixMap(read_pixel)

In [12]:
cat.map_partitions(lambda df: df, meta={"wrong": float})

MapPartitions(lambda, FromHealpixMap(read_pixel))

In [13]:
cat.map_partitions(lambda df: df, meta={"wrong": float}).compute()

Computing Catalog:   0%|          | 0/8 [00:00<?, ?it/s]

ValueError: Metadata mismatch found in `wrapped_func`.

Partition type: `nested_pandas.nestedframe.core.NestedFrame`
+-------------+-----------------+----------+
| Column      | Found           | Expected |
+-------------+-----------------+----------+
| 'dec'       | double[pyarrow] | -        |
| 'dec_error' | int64[pyarrow]  | -        |
| 'id'        | int64[pyarrow]  | -        |
| 'ra'        | double[pyarrow] | -        |
| 'ra_error'  | int64[pyarrow]  | -        |
| 'wrong'     | -               | float64  |
+-------------+-----------------+----------+

In [7]:
cat["ra"]

MapPartitions(lambda, FromHealpixMap(read_pixel))

In [10]:
cat["ra"] > 320

MapPartitions(lambda, MapPartitions(lambda, FromHealpixMap(read_pixel)))

In [11]:
cat[["ra", "dec"]] > 320

ValueError: Operator '>' requires a single-column catalog. Use catalog['column_name'] to select a column first.

In [14]:
cat[cat["ra"] > 320]

AlignAndApply(filter_func, FromHealpixMap(read_pixel), MapPartitions(lambda, MapPartitions(lambda, FromHealpixMap(read_pixel))))

In [15]:
cat[cat["ra"] > 320].compute()

Computing Catalog:   0%|          | 0/16 [00:00<?, ?it/s]

                      id     ra   dec  ra_error  dec_error
_healpix_29
3187796123455121090  792  320.5 -69.5         0          0
3192670279995812269  826  335.5 -69.5         0          0
...                  ...    ...   ...       ...        ...
3312697108463383701  803  336.5 -25.5         0          0
3391463069396352355  796  320.5 -33.5         0          0

[48 rows x 5 columns]