# Pandas 3 Large Strings

In [1]:
from nested_pandas.datasets import generate_data

In [3]:
nf = generate_data(5,10)
nf

          a         b                                             nested
0  0.177115  0.159462  [{t: 15.662955, flux: 51.449546, flux_error: 1...
1  0.698520  0.461675  [{t: 12.198509, flux: 9.558747, flux_error: 1....
2  0.230265  0.880809  [{t: 17.838907, flux: 67.60615, flux_error: 1....
3  0.631833  1.769112  [{t: 1.09051, flux: 14.041327, flux_error: 1.0...
4  0.786054  1.179150  [{t: 3.484588, flux: 22.197082, flux_error: 1....

In [9]:
nf["nested.band"]

0    g
0    g
    ..
4    g
4    r
Name: band, Length: 50, dtype: large_string[pyarrow]

In [28]:
import pyarrow as pa
import pandas as pd

print(f"large_string: {nf["nested.band"].nbytes} bytes")
print(f'string: {nf["nested.band"].astype(pd.ArrowDtype(pa.string())).nbytes} bytes')

large_string: 457 bytes
string: 257 bytes

In [32]:
import lsdb
gaia = lsdb.open_catalog('s3://stpubdata/gaia/gaia_dr3/public/hats')
gaia

FromHealpixMap(read_pixel)

In [37]:
gaia_nf = gaia.head(0)
gaia_nf.dtypes

solution_id                int64[pyarrow]
designation               string[pyarrow]
                               ...
ebpminrp_gspphot_upper     float[pyarrow]
libname_gspphot           string[pyarrow]
Length: 152, dtype: object